image: Visual Studio 2017
build_script:
  - ps: & .\build.cmd
on_failure:
  - appveyor PushArtifact FAKE.svclog
test: off
environment:
  PAKET_BOOTSTRAPPER_TRACE: true

artifacts:
  - path: 'bin\Grass.Web'
